### ISSUE TITLE
LinkList Algorithms Missing

### ISSUE THREAD

**Issue by shauryauppal** [eduardorasgado/CppZerotoAdvance2018#1]
@eduardorasgado If you allow a PR for this, I would send a PR.

**Comment by eduardorasgado** [comment]
Send me your PR, and feel free to fork the repo if you like, I will develop heap, stack, trees and linked lists  in a month(+/-). Cheers.

**Comment by shauryauppal** [comment]
@eduardorasgado in which section should I added link list code.

**Comment by shauryauppal** [comment]
Intermediate should be fine, I guess.
